### ISSUE TITLE
Cluster fails to start normally after shutdown

### ISSUE THREAD

**Issue by denismakogon** [mattlord/Docker-InnoDB-Cluster#13]
docker-compose file for cluster:
```
version: '3'
services:

  mysql-initiator:
    image: "mattalord/innodb-cluster"
    restart: always
    environment:
      - "MYSQL_DATABASE=funcs"
      - "MYSQL_ROOT_PASSWORD=root"
      - "GROUP_NAME=C55153C1-1574-4972-BF06-7332D6AD46A7"
      - "BOOTSTRAP=1"
    volumes:
      - ./data/mysql-initiator:/var/lib/mysql
  mysql-2:
    image: "mattalord/innodb-cluster"
    restart: always
    environment:
      - "MYSQL_DATABASE=funcs"
      - "MYSQL_ROOT_PASSWORD=root"
      - "GROUP_NAME=C55153C1-1574-4972-BF06-7332D6AD46A7"
      - "GROUP_SEEDS=mysql-initiator:6606"
    volumes:
      - ./data/mysql-member-2:/var/lib/mysql
    depends_on:
      - mysql-initiator
  mysql-3:
    image: "mattalord/innodb-cluster"
    restart: always
    environment:
      - "MYSQL_DATABASE=funcs"
      - "MYSQL_ROOT_PASSWORD=root"
      - "GROUP_NAME=C55153C1-1574-4972-BF06-7332D6AD46A7"
      - "GROUP_SEEDS=mysql-initiator:6606"
    volumes:
      - ./data/mysql-member-3:/var/lib/mysql
    depends_on:
      - mysql-initiator
  router:
    image: "mattalord/innodb-cluster"
    restart: always
    ports:
      - "3306:3306"
      - "6446-6447:6446-6447"
      - "6606:6606"
      - "33060:33060"
    volumes:
      - ./data/mysql-router:/var/lib/mysqlrouter
      - ./data/mysql-router-data:/var/lib/mysql
    depends_on:
      - mysql-initiator
      - mysql-2
      - mysql-3
    environment:
      - "NODE_TYPE=router"
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_HOST=mysql-initiator"
```
Initial provisioning works fine, but when deployment gets suspended or restarted. Cluster provisioning fails.
